# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'albertiWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.alberti_cypher import Alberti as alb


class Ui_Alberti(object):
    def setupUi(self, Alberti):
        Alberti.setObjectName("Alberti")
        Alberti.resize(482, 374)
        self.layoutWidget = QtWidgets.QWidget(Alberti)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 421, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.key = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.horizontalLayout.addWidget(self.key)
        self.shiftLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shiftLabel.setFont(font)
        self.shiftLabel.setObjectName("shiftLabel")
        self.horizontalLayout.addWidget(self.shiftLabel)
        self.shift = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shift.setFont(font)
        self.shift.setObjectName("shift")
        self.horizontalLayout.addWidget(self.shift)
        self.lang = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang.setFont(font)
        self.lang.setObjectName("lang")
        self.lang.addItem("")
        self.lang.addItem("")
        self.horizontalLayout.addWidget(self.lang)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.encrypt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout_2.addWidget(self.encrypt)
        self.decrypt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout_2.addWidget(self.decrypt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.output = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Alberti)
        QtCore.QMetaObject.connectSlotsByName(Alberti)

        self.encrypt.clicked.connect(self.encryptText)
        self.decrypt.clicked.connect(self.decryptText)
        self.lang.currentTextChanged.connect(self.changeShift)

        self.changeShift()

    def encryptText(self):
        plaintext = self.input.toPlainText()
        key = self.key.text()
        lang = self.lang.currentText()
        shift = self.shift.currentText()
        cyphertext = alb(key, shift, lang).encrypt(plaintext)
        self.output.setText(cyphertext)

    def decryptText(self):
        cyphertext = self.input.toPlainText()
        key = self.key.text()
        lang = self.lang.currentText()
        shift = self.shift.currentText()
        plaintext = alb(key, shift, lang).decrypt(cyphertext)
        self.output.setText(plaintext)

    def changeShift(self):
        self.shift.clear()
        lang = self.lang.currentText()

        for number in range(1, 26 if lang == 'ENG' else 33):
            self.shift.addItem(str(number))

    def retranslateUi(self, Alberti):
        _translate = QtCore.QCoreApplication.translate
        Alberti.setWindowTitle(_translate("Alberti", "Alberti"))
        self.cypherName.setText(_translate("Alberti", "Альберти"))
        self.key.setPlaceholderText(_translate("Alberti", "Ключ"))
        self.shiftLabel.setText(_translate("Alberti", "Смещение:"))
        self.lang.setItemText(0, _translate("Alberti", "ENG"))
        self.lang.setItemText(1, _translate("Alberti", "RUS"))
        self.encrypt.setText(_translate("Alberti", "Зашифровать"))
        self.decrypt.setText(_translate("Alberti", "Расшифровать"))
