# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardanoGrilleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

from cyphers.cardano_grille_cypher import CardanoGrille as cg


class Ui_CardanoGrille(object):
    def setupUi(self, CardanoGrille):
        CardanoGrille.setObjectName("CardanoGrille")
        CardanoGrille.resize(994, 587)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(CardanoGrille)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 20, 531, 541))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.input = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encode = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encode.setFont(font)
        self.encode.setObjectName("encode")
        self.horizontalLayout.addWidget(self.encode)
        self.decode = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decode.setFont(font)
        self.decode.setObjectName("decode")
        self.horizontalLayout.addWidget(self.decode)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.size = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.size.setObjectName("size")
        self.horizontalLayout.addWidget(self.size)
        self.jambled = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.jambled.setFont(font)
        self.jambled.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.jambled.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.jambled.setChecked(True)
        self.jambled.setObjectName("jambled")
        self.horizontalLayout.addWidget(self.jambled)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.grille = QtWidgets.QTableWidget(CardanoGrille)
        self.grille.setGeometry(QtCore.QRect(610, 130, 351, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grille.setFont(font)
        self.grille.setObjectName("grille")
        self.grille.setColumnCount(0)
        self.grille.setRowCount(0)

        self.retranslateUi(CardanoGrille)
        QtCore.QMetaObject.connectSlotsByName(CardanoGrille)

        self.encode.clicked.connect(self.encodeText)
        self.decode.clicked.connect(self.decodeText)

        self.jambled.stateChanged.connect(self.changeSizes)
        self.size.currentTextChanged.connect(self.sizeChanged)

        if self.jambled.isChecked():
            for i in range(3, 21):
                self.size.addItem(str(i))

        self.cardanoGrille = cg(int(self.size.currentText()), self.jambled.isChecked())

        self.input.setText('ABCDEFGHIJKLMNOP')

    def encodeText(self):
        plaintext = self.input.toPlainText()
        cyphertext = self.cardanoGrille.encode(plaintext)
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.input.toPlainText()
        plaintext = self.cardanoGrille.decode(cyphertext)
        self.output.setText(plaintext)

    def changeSizes(self):
        self.size.clear()
        if self.jambled.isChecked():
            numbers = [str(i) for i in range(3, 21)]
        else:
            numbers = [str(i) for i in range(4, 21, 2)]

        self.size.addItems(numbers)

        self.sizeChanged()

    def changeGrille(self):
        grille = self.cardanoGrille.whole_grille()
        for i in range(self.cardanoGrille.size):
            for j in range(self.cardanoGrille.size):
                self.grille.setItem(i, j, QTableWidgetItem(str(int(grille[i, j]))))
                self.grille.item(i, j).setTextAlignment(QtCore.Qt.AlignCenter)
                if self.cardanoGrille.grille[i, j] != 0:
                    self.grille.item(i, j).setBackground(QtGui.QColor('#1b877e'))
        self.grille.verticalHeader().setDefaultSectionSize(321 // self.cardanoGrille.size - 1)
        self.grille.horizontalHeader().setDefaultSectionSize(331 // self.cardanoGrille.size - 1)

    def sizeChanged(self):
        if self.size.currentText() != '':
            self.cardanoGrille = cg(int(self.size.currentText()), self.jambled.isChecked())
            self.grille.setColumnCount(self.cardanoGrille.size)
            self.grille.setRowCount(self.cardanoGrille.size)

            self.changeGrille()

    def retranslateUi(self, CardanoGrille):
        _translate = QtCore.QCoreApplication.translate
        CardanoGrille.setWindowTitle(_translate("CardanoGrille", "Cardano Grille"))
        self.label_2.setText(_translate("CardanoGrille", "Решётка Кардано"))
        self.encode.setText(_translate("CardanoGrille", "Зашифровать"))
        self.decode.setText(_translate("CardanoGrille", "Расшифровать"))
        self.label.setText(_translate("CardanoGrille", "Размер:"))
        self.jambled.setText(_translate("CardanoGrille", "С мусором"))
