# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ceasarWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.caesar_cypher import Ceasar


class Ui_Ceasar(object):
    def setupUi(self, Ceasar):
        Ceasar.setObjectName("Ceasar")
        Ceasar.resize(478, 373)
        self.verticalLayoutWidget = QtWidgets.QWidget(Ceasar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(59, 20, 371, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textInput = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textInput.setFont(font)
        self.textInput.setObjectName("textInput")
        self.verticalLayout.addWidget(self.textInput)
        self.keyInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.keyInput.setFont(font)
        self.keyInput.setObjectName("keyInput")
        self.verticalLayout.addWidget(self.keyInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encode.setFont(font)
        self.encode.setObjectName("encode")
        self.horizontalLayout.addWidget(self.encode)
        self.decode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decode.setFont(font)
        self.decode.setObjectName("decode")
        self.horizontalLayout.addWidget(self.decode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Ceasar)
        QtCore.QMetaObject.connectSlotsByName(Ceasar)

        self.encode.clicked.connect(self.encodeText)
        self.decode.clicked.connect(self.decodeText)

    def encodeText(self):
        plaintext = self.textInput.toPlainText()
        ceas = Ceasar()
        cyphertext = ceas.encode(plaintext, self.keyInput.text())
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.textInput.toPlainText()
        ceas = Ceasar()
        plaintext = ceas.decode(cyphertext, self.keyInput.text())
        self.output.setText(plaintext)

    def retranslateUi(self, Ceasar):
        _translate = QtCore.QCoreApplication.translate
        Ceasar.setWindowTitle(_translate("Ceasar", "Ceasar"))
        self.label.setText(_translate("Ceasar", "Цезарь"))
        self.encode.setText(_translate("Ceasar", "Зашифровать"))
        self.decode.setText(_translate("Ceasar", "Расшифровать"))
