# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import docx
import fitz
from striprtf.striprtf import rtf_to_text

from cyphers.des_cypher import DES as Des


class Ui_DES(object):
    def setupUi(self, DES):
        DES.setObjectName("DES")
        DES.resize(753, 579)
        self.widget = QtWidgets.QWidget(DES)
        self.widget.setGeometry(QtCore.QRect(70, 20, 621, 541))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.key = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout.addWidget(self.encrypt)
        self.decrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout.addWidget(self.decrypt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.read = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.read.setFont(font)
        self.read.setObjectName("read")
        self.horizontalLayout_2.addWidget(self.read)
        self.write = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write.setFont(font)
        self.write.setObjectName("write")
        self.horizontalLayout_2.addWidget(self.write)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.output = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(DES)
        QtCore.QMetaObject.connectSlotsByName(DES)

        self.des = Des()

        self.encrypt.clicked.connect(self.encryptText)
        self.decrypt.clicked.connect(self.decryptText)

        self.read.clicked.connect(self.readFromFile)
        self.write.clicked.connect(self.writeToFile)

    def encryptText(self):
        encrypted_text = self.des.encrypt(self.input.toPlainText(), self.key.text())
        self.output.setText(encrypted_text)

    def decryptText(self):
        decrypted_text = self.des.decrypt(self.input.toPlainText(), self.key.text())
        self.output.setText(decrypted_text)

    def readFromFile(self):
        path = QFileDialog.getOpenFileName()[0]
        extension = path.split('/')[-1].split('.')[-1]

        if extension == 'txt':
            with open(path, 'r', encoding='utf-8') as file:
                self.input.setText(file.read())

        elif extension == 'docx':
            doc = docx.Document(path)
            text = []
            for para in doc.paragraphs:
                text.append(para.text)
            self.input.setText(''.join(text))

        elif extension == 'rtf':
            with open(path, 'r', encoding='utf-8') as file:
                content = file.read()
                self.input.setText(rtf_to_text(content))

        elif extension == 'pdf':
            with fitz.open(path) as file:
                text = ''
                for page in file:
                    text += page.get_text()
                self.input.setText(rtf_to_text(text))

    def writeToFile(self):
        path = QFileDialog.getOpenFileName()[0]
        with open(path, 'w+', encoding='utf-8') as file:
            file.write(self.output.toPlainText())

    def retranslateUi(self, DES):
        _translate = QtCore.QCoreApplication.translate
        DES.setWindowTitle(_translate("DES", "DES"))
        self.cypherName.setText(_translate("DES", "Data Encryption Standard"))
        self.encrypt.setText(_translate("DES", "Зашифровать"))
        self.decrypt.setText(_translate("DES", "Расшифровать"))
        self.read.setText(_translate("DES", "Открыть файл"))
        self.write.setText(_translate("DES", "Записать в файл"))
