# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elgamalWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from random import randint

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QFileDialog

from cyphers.elgamal_cypher import ElGamal as elgamal
from cyphers.diffie_hellman_protocol import generate_p_q_g
from utils.basic_algorithms.powmod import powmod


class Ui_ElGamal(object):
    def setupUi(self, ElGamal):
        ElGamal.setObjectName("ElGamal")
        ElGamal.resize(1015, 894)
        self.layoutWidget = QtWidgets.QWidget(ElGamal)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 941, 831))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.bits = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bits.sizePolicy().hasHeightForWidth())
        self.bits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bits.setFont(font)
        self.bits.setObjectName("bits")
        self.horizontalLayout_4.addWidget(self.bits)
        self.generate_pqg = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generate_pqg.setFont(font)
        self.generate_pqg.setObjectName("generate_pqg")
        self.horizontalLayout_4.addWidget(self.generate_pqg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.p = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p.setFont(font)
        self.p.setReadOnly(True)
        self.p.setObjectName("p")
        self.horizontalLayout.addWidget(self.p)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.q = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.q.setFont(font)
        self.q.setReadOnly(True)
        self.q.setObjectName("q")
        self.horizontalLayout_2.addWidget(self.q)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.g = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.g.setFont(font)
        self.g.setReadOnly(True)
        self.g.setObjectName("g")
        self.horizontalLayout_3.addWidget(self.g)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.generate_keys = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generate_keys.setFont(font)
        self.generate_keys.setObjectName("generate_keys")
        self.verticalLayout_3.addWidget(self.generate_keys)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.public_key_a = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.public_key_a.setFont(font)
        self.public_key_a.setReadOnly(True)
        self.public_key_a.setObjectName("public_key_a")
        self.verticalLayout.addWidget(self.public_key_a)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.private_key_a = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.private_key_a.setFont(font)
        self.private_key_a.setReadOnly(True)
        self.private_key_a.setObjectName("private_key_a")
        self.verticalLayout.addWidget(self.private_key_a)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.public_key_b = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.public_key_b.setFont(font)
        self.public_key_b.setReadOnly(True)
        self.public_key_b.setObjectName("public_key_b")
        self.verticalLayout_2.addWidget(self.public_key_b)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.private_key_b = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.private_key_b.setFont(font)
        self.private_key_b.setReadOnly(True)
        self.private_key_b.setObjectName("private_key_b")
        self.verticalLayout_2.addWidget(self.private_key_b)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout_4.addWidget(self.input)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.encrypt_text = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt_text.setFont(font)
        self.encrypt_text.setObjectName("encrypt_text")
        self.horizontalLayout_10.addWidget(self.encrypt_text)
        self.decrypt_text = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt_text.setFont(font)
        self.decrypt_text.setObjectName("decrypt_text")
        self.horizontalLayout_10.addWidget(self.decrypt_text)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.output_3 = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_3.setFont(font)
        self.output_3.setReadOnly(True)
        self.output_3.setObjectName("output_3")
        self.verticalLayout_4.addWidget(self.output_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.inputFileText = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputFileText.setFont(font)
        self.inputFileText.setObjectName("inputFileText")
        self.horizontalLayout_7.addWidget(self.inputFileText)
        self.inputFilePath = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inputFilePath.setFont(font)
        self.inputFilePath.setObjectName("inputFilePath")
        self.horizontalLayout_7.addWidget(self.inputFilePath)
        self.inputFilePathButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputFilePathButton.setFont(font)
        self.inputFilePathButton.setObjectName("inputFilePathButton")
        self.horizontalLayout_7.addWidget(self.inputFilePathButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.outputFileText = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputFileText.setFont(font)
        self.outputFileText.setObjectName("outputFileText")
        self.horizontalLayout_9.addWidget(self.outputFileText)
        self.outputFilePath = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.outputFilePath.setFont(font)
        self.outputFilePath.setObjectName("outputFilePath")
        self.horizontalLayout_9.addWidget(self.outputFilePath)
        self.outputFilePathButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputFilePathButton.setFont(font)
        self.outputFilePathButton.setObjectName("outputFilePathButton")
        self.horizontalLayout_9.addWidget(self.outputFilePathButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.encrypt_file = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt_file.setFont(font)
        self.encrypt_file.setObjectName("encrypt_file")
        self.horizontalLayout_8.addWidget(self.encrypt_file)
        self.decrypt_file = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt_file.setFont(font)
        self.decrypt_file.setObjectName("decrypt_file")
        self.horizontalLayout_8.addWidget(self.decrypt_file)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.cypherName = QtWidgets.QLabel(ElGamal)
        self.cypherName.setGeometry(QtCore.QRect(30, 10, 959, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.output = QtWidgets.QTextEdit(ElGamal)
        self.output.setGeometry(QtCore.QRect(40, 1163, 939, 192))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.output_2 = QtWidgets.QTextEdit(ElGamal)
        self.output_2.setGeometry(QtCore.QRect(620, 1243, 939, 192))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_2.setFont(font)
        self.output_2.setReadOnly(True)
        self.output_2.setObjectName("output_2")
        self.input_2 = QtWidgets.QTextEdit(ElGamal)
        self.input_2.setGeometry(QtCore.QRect(620, 1010, 939, 192))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_2.setFont(font)
        self.input_2.setObjectName("input_2")

        self.retranslateUi(ElGamal)
        QtCore.QMetaObject.connectSlotsByName(ElGamal)

        self.elgamal = elgamal()

        self.bits.setText('1024')

        reg_ex = QRegExp(r'[1-9]{1}[0-9]+')
        input_validator = QRegExpValidator(reg_ex, self.bits)
        self.bits.setValidator(input_validator)

        self.generate_pqg.clicked.connect(self.generatePQG)
        self.generate_keys.clicked.connect(self.generateKeys)
        self.encrypt_text.clicked.connect(self.encryptText)
        self.decrypt_text.clicked.connect(self.decryptText)
        self.encrypt_file.clicked.connect(self.encryptFile)
        self.decrypt_file.clicked.connect(self.decryptFile)
        self.inputFilePathButton.clicked.connect(lambda: self.getPath(self.inputFilePath))
        self.outputFilePathButton.clicked.connect(lambda: self.getPath(self.outputFilePath))

    def generatePQG(self):
        try:
            if int(self.bits.text()) >= 8:
                p, q, g = generate_p_q_g(int(self.bits.text()))
                self.p.setText(str(p))
                self.q.setText(str(q))
                self.g.setText(str(g))
        except:
            pass

    def generateKeys(self):
        if self.p.text() and self.q.text() and self.g.text() and int(self.bits.text()) >= 2:
            private_key_a, private_key_b = randint(2 ** (int(self.bits.text()) - 1), 2 ** int(self.bits.text())), \
                                           randint(2 ** (int(self.bits.text()) - 1), 2 ** int(self.bits.text()))

            while private_key_a == private_key_b:
                private_key_b = randint(2 ** (int(self.bits.text())) - 1, 2 ** int(self.bits.text()))

            public_key_a, public_key_b = powmod(int(self.g.text()), private_key_a, int(self.p.text())), \
                                         powmod(int(self.g.text()), private_key_b, int(self.p.text()))

            self.public_key_a.setText(str(public_key_a))
            self.public_key_b.setText(str(public_key_b))
            self.private_key_a.setText(str(private_key_a))
            self.private_key_b.setText(str(private_key_b))

    def encryptText(self):
        try:
            if self.input.toPlainText():
                encrypted_text = self.elgamal.encrypt(self.input.toPlainText(),
                                                      int(self.g.text()),
                                                      int(self.public_key_b.toPlainText()),
                                                      int(self.p.text()))
                self.output_3.setText(encrypted_text)
        except:
            pass

    def decryptText(self):
        try:
            if self.input.toPlainText():
                decrypted_text = self.elgamal.decrypt(self.input.toPlainText(),
                                                      int(self.private_key_b.toPlainText()),
                                                      int(self.p.text()))
                self.output_3.setText(decrypted_text)
        except:
            pass

    def encryptFile(self):
        if self.outputFilePath.text() and self.inputFilePath.text():
            self.elgamal.encrypt('',
                                 int(self.g.text()),
                                 int(self.public_key_b.toPlainText()),
                                 int(self.p.text()),
                                 self.inputFilePath.text(),
                                 self.outputFilePath.text())

    def decryptFile(self):
        if self.outputFilePath.text() and self.inputFilePath.text():
            self.elgamal.decrypt('',
                                 int(self.private_key_b.toPlainText()),
                                 int(self.p.text()),
                                 self.inputFilePath.text(),
                                 self.outputFilePath.text())

    def getPath(self, obj):
        path = QFileDialog.getOpenFileName()[0]
        if path[-3:] != 'elg':
            self.outputFilePath.setText(path + '.elg')
        else:
            self.outputFilePath.setText(path[:-4])
        obj.setText(path)

    def retranslateUi(self, ElGamal):
        _translate = QtCore.QCoreApplication.translate
        ElGamal.setWindowTitle(_translate("ElGamal", "ElGamal"))
        self.label_5.setText(_translate("ElGamal", "Количество бит"))
        self.generate_pqg.setText(_translate("ElGamal", "Сгенерировать"))
        self.label.setText(_translate("ElGamal", "p"))
        self.label_2.setText(_translate("ElGamal", "q"))
        self.label_3.setText(_translate("ElGamal", "g"))
        self.generate_keys.setText(_translate("ElGamal", "Вычислить ключи"))
        self.label_6.setText(_translate("ElGamal", "Открытый ключ A"))
        self.label_8.setText(_translate("ElGamal", "Закрытый ключ A"))
        self.label_7.setText(_translate("ElGamal", "Открытый ключ B"))
        self.label_9.setText(_translate("ElGamal", "Закрытый ключ B"))
        self.encrypt_text.setText(_translate("ElGamal", "Зашифровать"))
        self.decrypt_text.setText(_translate("ElGamal", "Расшифровать"))
        self.inputFileText.setText(_translate("ElGamal", "Входной файл  "))
        self.inputFilePathButton.setText(_translate("ElGamal", "Указать путь"))
        self.outputFileText.setText(_translate("ElGamal", "Выходной файл"))
        self.outputFilePathButton.setText(_translate("ElGamal", "Указать путь"))
        self.encrypt_file.setText(_translate("ElGamal", "Зашифровать"))
        self.decrypt_file.setText(_translate("ElGamal", "Расшифровать"))
        self.cypherName.setText(_translate("ElGamal", "ElGamal"))
