# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gronsfeldWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.gronsfeld_cypher import Gronsfeld as gr


class Ui_Gronsfeld(object):
    def setupUi(self, Gronsfeld):
        Gronsfeld.setObjectName("Gronsfeld")
        Gronsfeld.resize(484, 380)
        self.widget = QtWidgets.QWidget(Gronsfeld)
        self.widget.setGeometry(QtCore.QRect(40, 10, 411, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.key = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout.addWidget(self.encrypt)
        self.decrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout.addWidget(self.decrypt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Gronsfeld)
        QtCore.QMetaObject.connectSlotsByName(Gronsfeld)

        self.encrypt.clicked.connect(self.encodeText)
        self.decrypt.clicked.connect(self.decodeText)

        self.gronsfeld = gr()

    def encodeText(self):
        plaintext = self.input.toPlainText()
        key = self.key.text()
        cyphertext = self.gronsfeld.encode(plaintext, key)
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.input.toPlainText()
        key = self.key.text()
        plaintext = self.gronsfeld.decode(cyphertext, key)
        self.output.setText(plaintext)

    def retranslateUi(self, Gronsfeld):
        _translate = QtCore.QCoreApplication.translate
        Gronsfeld.setWindowTitle(_translate("Gronsfeld", "Gronsfeld"))
        self.label.setText(_translate("Gronsfeld", "Гронсфельд"))
        self.encrypt.setText(_translate("Gronsfeld", "Зашифровать"))
        self.decrypt.setText(_translate("Gronsfeld", "Расшифровать"))
