# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hillWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import numpy as np

from cyphers.hill_cypher import Hill as hill


class Ui_Hill(object):
    def setupUi(self, Hill):
        Hill.setObjectName("Hill")
        Hill.resize(763, 385)
        self.layoutWidget = QtWidgets.QWidget(Hill)
        self.layoutWidget.setGeometry(QtCore.QRect(37, 20, 411, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encrypt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout.addWidget(self.encrypt)
        self.decrypt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout.addWidget(self.decrypt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.key = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setClearButtonEnabled(False)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.output = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.alphabet = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.alphabet.setFont(font)
        self.alphabet.setObjectName("alphabet")
        self.verticalLayout.addWidget(self.alphabet)
        self.key_matrix = QtWidgets.QTableWidget(Hill)
        self.key_matrix.setGeometry(QtCore.QRect(480, 80, 250, 250))
        self.key_matrix.setObjectName("key_matrix")
        self.key_matrix.setColumnCount(0)
        self.key_matrix.setRowCount(0)
        self.message = QtWidgets.QLabel(Hill)
        self.message.setGeometry(QtCore.QRect(486, 50, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.message.setFont(font)
        self.message.setText("")
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setObjectName("message")

        self.retranslateUi(Hill)
        QtCore.QMetaObject.connectSlotsByName(Hill)

        self.encrypt.clicked.connect(self.encodeText)
        self.decrypt.clicked.connect(self.decodeText)
        self.key.textChanged.connect(self.updateKey)
        self.alphabet.textChanged.connect(self.updateKey)

        self.key.setText("KEKW")
        self.alphabet.setText("ABCDEFGHIJKLMNOPQRSTUVWXYZ .?")

        self.key.setPlaceholderText('Длина ключа - квадрат числа')

        self.hill = hill(self.key.text(), self.alphabet.text())

    def encodeText(self):
        plaintext = self.input.toPlainText()
        cyphertext = self.hill.encode(plaintext)
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.input.toPlainText()
        plaintext = self.hill.decode(cyphertext)
        self.output.setText(plaintext)

    def updateKey(self):
        self.hill = hill(self.key.text(), self.alphabet.text())

        if self.hill.is_correct_key():
            key = self.hill.key
            n = round(np.sqrt(len(key)))
            key_matrix = np.array([self.hill.LETTERS.index(letter) for letter in key]).reshape((n, n))
            inv_matrix = self.hill.invert_matrix(key_matrix)

            if not np.all(inv_matrix):
                self.message.setText("Матрица необратима")
            else:
                self.message.setText("")

            self.updateTable(n)
        else:
            self.message.setText("")
            self.key_matrix.setRowCount(0)
            self.key_matrix.setColumnCount(0)

    def updateTable(self, n):
        key = self.hill.key

        self.key_matrix.setRowCount(n)
        self.key_matrix.setColumnCount(n)
        self.key_matrix.verticalHeader().setDefaultSectionSize(220 // n - 1)
        self.key_matrix.horizontalHeader().setDefaultSectionSize(229 // n - 1)

        for i in range(n):
            for j in range(n):
                self.key_matrix.setItem(i, j, QTableWidgetItem(str(self.hill.LETTERS.index(key[i*n+j]))))
                self.key_matrix.item(i, j).setTextAlignment(QtCore.Qt.AlignCenter)

    def retranslateUi(self, Hill):
        _translate = QtCore.QCoreApplication.translate
        Hill.setWindowTitle(_translate("Hill", "Hill"))
        self.cypherName.setText(_translate("Hill", "Хилл"))
        self.encrypt.setText(_translate("Hill", "Зашифровать"))
        self.decrypt.setText(_translate("Hill", "Расшифровать"))
        self.alphabet.setPlaceholderText(_translate("Hill", "Алфавит"))
