# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from .atbashWindow import Ui_Atbash


class Ui_MainWindow(object):
    def doubleClicked(self, item):
        cypher = item.text().split()[0]
        if cypher == 'Atbash':
            self.atbashDialog()

    def atbashDialog(self):
        self.atbash = QtWidgets.QMainWindow()
        self.ui = Ui_Atbash()
        self.ui.setupUi(self.atbash)
        self.atbash.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 598)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 691, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cyphersList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cyphersList.setFont(font)
        self.cyphersList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cyphersList.setAutoFillBackground(False)
        self.cyphersList.setStyleSheet("")
        self.cyphersList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.cyphersList.setViewMode(QtWidgets.QListView.ListMode)
        self.cyphersList.setItemAlignment(QtCore.Qt.AlignCenter)
        self.cyphersList.setObjectName("cyphersList")
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cyphersList.addItem(item)
        self.verticalLayout.addWidget(self.cyphersList)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.cyphersList.itemDoubleClicked.connect(self.doubleClicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cryptographic Methods of Information Security"))
        self.label.setText(_translate("MainWindow", "Метод:"))
        __sortingEnabled = self.cyphersList.isSortingEnabled()
        self.cyphersList.setSortingEnabled(False)
        item = self.cyphersList.item(0)
        item.setText(_translate("MainWindow", "Atbash cypher"))
        item = self.cyphersList.item(1)
        item.setText(_translate("MainWindow", "Scytala cypher"))
        item = self.cyphersList.item(2)
        item.setText(_translate("MainWindow", "Polibius Square cypher"))
        item = self.cyphersList.item(3)
        item.setText(_translate("MainWindow", "Ceaser cypher"))
        item = self.cyphersList.item(4)
        item.setText(_translate("MainWindow", "Cardano cypher"))
        item = self.cyphersList.item(5)
        item.setText(_translate("MainWindow", "Rishelieu cypher"))
        item = self.cyphersList.item(6)
        item.setText(_translate("MainWindow", "Alberti\'s Disk cypher"))
        item = self.cyphersList.item(7)
        item.setText(_translate("MainWindow", "Gronsfeld cypher"))
        item = self.cyphersList.item(8)
        item.setText(_translate("MainWindow", "Vigenere cypher"))
        item = self.cyphersList.item(9)
        item.setText(_translate("MainWindow", "Playfair cypher"))
        item = self.cyphersList.item(10)
        item.setText(_translate("MainWindow", "Hill cypher"))
        item = self.cyphersList.item(11)
        item.setText(_translate("MainWindow", "Vernam cypher"))
        self.cyphersList.setSortingEnabled(__sortingEnabled)
