# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md5Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from hashing.md5 import MD5 as md5


class Ui_MD5(object):
    def setupUi(self, MD5):
        MD5.setObjectName("MD5")
        MD5.resize(705, 377)
        self.widget = QtWidgets.QWidget(MD5)
        self.widget.setGeometry(QtCore.QRect(20, 10, 661, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.calculate = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculate.setFont(font)
        self.calculate.setObjectName("calculate")
        self.verticalLayout.addWidget(self.calculate)
        self.output = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.calculate_from_file = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculate_from_file.setFont(font)
        self.calculate_from_file.setObjectName("calculate_from_file")
        self.verticalLayout.addWidget(self.calculate_from_file)

        self.retranslateUi(MD5)
        QtCore.QMetaObject.connectSlotsByName(MD5)

        self.calculate.clicked.connect(self.calculate_hash)
        self.calculate_from_file.clicked.connect(self.calculate_hash_from_file)

    def calculate_hash(self):
        self.output.setText(md5(self.input.toPlainText()).generate_hash())

    def calculate_hash_from_file(self):
        path = QFileDialog.getOpenFileName()[0]
        self.output.setText(md5(path, type='file').generate_hash())

    def retranslateUi(self, MD5):
        _translate = QtCore.QCoreApplication.translate
        MD5.setWindowTitle(_translate("MD5", "MD5"))
        self.cypherName.setText(_translate("MD5", "MD5"))
        self.calculate.setText(_translate("MD5", "Вычислить"))
        self.calculate_from_file.setText(_translate("MD5", "Вычислить из файла"))
