# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playfairWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

from cyphers.playfair_cypher import Playfair as pl


class Ui_Playfair(object):
    def setupUi(self, Playfair):
        Playfair.setObjectName("Playfair")
        Playfair.resize(895, 624)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Playfair.sizePolicy().hasHeightForWidth())
        Playfair.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(Playfair)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 881, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(100)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.input = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout_10.addWidget(self.input)
        self.key = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout_10.addWidget(self.key)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.encrypt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout_14.addWidget(self.encrypt)
        self.decrypt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout_14.addWidget(self.decrypt)
        self.lang = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang.setFont(font)
        self.lang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lang.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.lang.setObjectName("lang")
        self.lang.addItem("")
        self.lang.addItem("")
        self.horizontalLayout_14.addWidget(self.lang)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout_10.addWidget(self.output)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.alphabet = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphabet.sizePolicy().hasHeightForWidth())
        self.alphabet.setSizePolicy(sizePolicy)
        self.alphabet.setMinimumSize(QtCore.QSize(250, 250))
        self.alphabet.setMaximumSize(QtCore.QSize(350, 257))
        self.alphabet.setObjectName("alphabet")
        self.alphabet.setColumnCount(0)
        self.alphabet.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.alphabet)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Playfair)
        QtCore.QMetaObject.connectSlotsByName(Playfair)

        self.encrypt.clicked.connect(self.encodeText)
        self.decrypt.clicked.connect(self.decodeText)

        self.lang.currentTextChanged.connect(self.updateKeyLang)

        self.playfair = pl(self.lang.currentText(), self.key.text())

        self.key.textChanged.connect(self.updateKeyLang)

    def encodeText(self):
        plaintext = self.input.toPlainText()
        cyphertext = self.playfair.encode(plaintext)
        self.output.setText(cyphertext)

        if cyphertext:
            self.updateAlphabet()

    def decodeText(self):
        cyphertext = self.input.toPlainText()
        plaintext = self.playfair.decode(cyphertext)
        self.output.setText(plaintext)

        if plaintext:
            self.updateAlphabet()

    def updateKeyLang(self):
        self.playfair = pl(self.lang.currentText(), self.key.text())

    def updateAlphabet(self):
        matrix = self.playfair.generate_matrix()

        n = matrix.shape[0]
        m = matrix.shape[1]

        self.alphabet.setRowCount(n)
        self.alphabet.setColumnCount(m)

        if self.playfair.lang == 'ENG':
            width = 239
            height = 233
        else:
            width = 239
            height = 220

        self.alphabet.horizontalHeader().setDefaultSectionSize(width // m - 1)
        self.alphabet.verticalHeader().setDefaultSectionSize(height // n - 1)

        for i in range(n):
            for j in range(m):
                self.alphabet.setItem(i, j, QTableWidgetItem(matrix[i, j]))
                self.alphabet.item(i, j).setTextAlignment(QtCore.Qt.AlignCenter)

    def retranslateUi(self, Playfair):
        _translate = QtCore.QCoreApplication.translate
        Playfair.setWindowTitle(_translate("Playfair", "Playfair"))
        self.label_2.setText(_translate("Playfair", "Плейфер"))
        self.encrypt.setText(_translate("Playfair", "Зашифровать"))
        self.decrypt.setText(_translate("Playfair", "Расшифровать"))
        self.lang.setItemText(0, _translate("Playfair", "ENG"))
        self.lang.setItemText(1, _translate("Playfair", "RUS"))
