# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polybiusSquareWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.polybius_square_cypher import PolybiusSquare as ps


class Ui_PolybiusSquare(object):
    def setupUi(self, PolybiusSquare):
        PolybiusSquare.setObjectName("PolybiusSquare")
        PolybiusSquare.resize(480, 374)
        self.verticalLayoutWidget = QtWidgets.QWidget(PolybiusSquare)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 382, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.input = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encrypt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout.addWidget(self.encrypt)
        self.method = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.method.setFont(font)
        self.method.setToolTipDuration(-1)
        self.method.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.method.setAutoFillBackground(False)
        self.method.setStyleSheet("")
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.horizontalLayout.addWidget(self.method)
        self.lang = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang.setFont(font)
        self.lang.setObjectName("lang")
        self.lang.addItem("")
        self.lang.addItem("")
        self.horizontalLayout.addWidget(self.lang)
        self.decrypt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout.addWidget(self.decrypt)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(PolybiusSquare)
        QtCore.QMetaObject.connectSlotsByName(PolybiusSquare)

        self.encrypt.clicked.connect(self.encodeText)
        self.decrypt.clicked.connect(self.decodeText)
        self.lang.currentTextChanged.connect(self.updateLang)

        self.polybius = ps(self.lang.currentText())

    def encodeText(self):
        plaintext = self.input.toPlainText()
        cyphertext = self.polybius.encode(plaintext, self.method.currentText()[-1])
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.input.toPlainText()
        plaintext = self.polybius.decode(cyphertext, self.method.currentText()[-1])
        self.output.setText(plaintext)

    def updateLang(self):
        self.polybius = ps(self.lang.currentText())

    def retranslateUi(self, PolybiusSquare):
        _translate = QtCore.QCoreApplication.translate
        PolybiusSquare.setWindowTitle(_translate("PolybiusSquare", "Polybius Square"))
        self.name.setText(_translate("PolybiusSquare", "Квадрат Полибия"))
        self.encrypt.setText(_translate("PolybiusSquare", "Зашифровать"))
        self.method.setItemText(0, _translate("PolybiusSquare", "Метод 1"))
        self.method.setItemText(1, _translate("PolybiusSquare", "Метод 2"))
        self.method.setItemText(2, _translate("PolybiusSquare", "Метод 3"))
        self.lang.setItemText(0, _translate("PolybiusSquare", "ENG"))
        self.lang.setItemText(1, _translate("PolybiusSquare", "RUS"))
        self.decrypt.setText(_translate("PolybiusSquare", "Расшифровать"))
