# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'richelieuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.richelieu_cypher import Richelieu


class Ui_Richelieu(object):
    def setupUi(self, Richelieu):
        Richelieu.setObjectName("Richelieu")
        Richelieu.resize(482, 378)
        self.verticalLayoutWidget = QtWidgets.QWidget(Richelieu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 20, 401, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.key = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.encodeDecode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encodeDecode.setFont(font)
        self.encodeDecode.setObjectName("encodeDecode")
        self.verticalLayout.addWidget(self.encodeDecode)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Richelieu)
        QtCore.QMetaObject.connectSlotsByName(Richelieu)

        self.encodeDecode.clicked.connect(self.encodeDecodeText)

    def encodeDecodeText(self):
        plaintext = self.input.toPlainText()
        key = self.key.text()
        rich = Richelieu()
        cyphertext = rich.encode(plaintext, key)
        self.output.setText(cyphertext)

    def retranslateUi(self, Richelieu):
        _translate = QtCore.QCoreApplication.translate
        Richelieu.setWindowTitle(_translate("Richelieu", "Richelieu"))
        self.label.setText(_translate("Richelieu", "Ришелье"))
        self.encodeDecode.setText(_translate("Richelieu", "Зашифровать/Расшифровать"))
