# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scytaleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.scytale_cypher import Scytale


class Ui_Scytale(object):
    def setupUi(self, Scytale):
        Scytale.setObjectName("Scytale")
        Scytale.resize(482, 375)
        self.verticalLayoutWidget = QtWidgets.QWidget(Scytale)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 371, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textInput = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textInput.setFont(font)
        self.textInput.setObjectName("textInput")
        self.verticalLayout.addWidget(self.textInput)
        self.keyInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.keyInput.setFont(font)
        self.keyInput.setObjectName("keyInput")
        self.verticalLayout.addWidget(self.keyInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encode.setFont(font)
        self.encode.setObjectName("encode")
        self.horizontalLayout.addWidget(self.encode)
        self.decode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decode.setFont(font)
        self.decode.setObjectName("decode")
        self.horizontalLayout.addWidget(self.decode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Scytale)
        QtCore.QMetaObject.connectSlotsByName(Scytale)

        self.encode.clicked.connect(self.encodeText)
        self.decode.clicked.connect(self.decodeText)

    def encodeText(self):
        plaintext = self.textInput.toPlainText()
        key = self.keyInput.text()
        scy = Scytale()
        cyphertext = scy.encode(plaintext, key)
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.textInput.toPlainText()
        key = self.keyInput.text()
        scy = Scytale()
        plaintext = scy.decode(cyphertext, key)
        self.output.setText(plaintext)

    def retranslateUi(self, Scytale):
        _translate = QtCore.QCoreApplication.translate
        Scytale.setWindowTitle(_translate("Scytale", "Scytale"))
        self.label.setText(_translate("Scytale", "Сцитала"))
        self.encode.setText(_translate("Scytale", "Зашифровать"))
        self.decode.setText(_translate("Scytale", "Расшифровать"))
