# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sha1Winow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from hashing.sha1 import SHA1 as sha1


class Ui_SHA1(object):
    def setupUi(self, SHA1):
        SHA1.setObjectName("SHA1")
        SHA1.resize(703, 375)
        self.layoutWidget = QtWidgets.QWidget(SHA1)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 661, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.calculate = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculate.setFont(font)
        self.calculate.setObjectName("calculate")
        self.verticalLayout.addWidget(self.calculate)
        self.output = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.calculate_from_file = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculate_from_file.setFont(font)
        self.calculate_from_file.setObjectName("calculate_from_file")
        self.verticalLayout.addWidget(self.calculate_from_file)

        self.retranslateUi(SHA1)
        QtCore.QMetaObject.connectSlotsByName(SHA1)

        self.calculate.clicked.connect(self.calculate_hash)
        self.calculate_from_file.clicked.connect(self.calculate_hash_from_file)

    def calculate_hash(self):
        self.output.setText(sha1(self.input.toPlainText()).generate_hash())

    def calculate_hash_from_file(self):
        path = QFileDialog.getOpenFileName()[0]
        self.output.setText(sha1(path, type='file').generate_hash())

    def retranslateUi(self, SHA1):
        _translate = QtCore.QCoreApplication.translate
        SHA1.setWindowTitle(_translate("SHA1", "SHA1"))
        self.cypherName.setText(_translate("SHA1", "SHA1"))
        self.calculate.setText(_translate("SHA1", "Вычислить"))
        self.calculate_from_file.setText(_translate("SHA1", "Вычислить из файла"))
