# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vernamWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.vernam_cypher import Vernam as ver


class Ui_Vernam(object):
    def setupUi(self, Vernam):
        Vernam.setObjectName("Vernam")
        Vernam.resize(486, 382)
        self.widget = QtWidgets.QWidget(Vernam)
        self.widget.setGeometry(QtCore.QRect(40, 20, 411, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.key = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.encryptDecrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encryptDecrypt.setFont(font)
        self.encryptDecrypt.setObjectName("encryptDecrypt")
        self.verticalLayout.addWidget(self.encryptDecrypt)
        self.output = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Vernam)
        QtCore.QMetaObject.connectSlotsByName(Vernam)

        self.encryptDecrypt.clicked.connect(self.encodeText)

        self.vernam = ver()

    def encodeText(self):
        text = self.input.toPlainText()
        key = self.key.text()
        enc_dec_text = self.vernam.encode(text, key)
        self.output.setText(enc_dec_text)

    def retranslateUi(self, Vernam):
        _translate = QtCore.QCoreApplication.translate
        Vernam.setWindowTitle(_translate("Vernam", "Vernam"))
        self.cypherName.setText(_translate("Vernam", "Вернам"))
        self.encryptDecrypt.setText(_translate("Vernam", "Зашифровать/Расшифровать"))
