# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vernamWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from random import choice

from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.vernam_cypher import Vernam as ver
from constants.constants import RUS_LETTERS


class Ui_Vernam(object):
    def setupUi(self, Vernam):
        Vernam.setObjectName("Vernam")
        Vernam.resize(486, 382)
        self.layoutWidget = QtWidgets.QWidget(Vernam)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 411, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.key = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.horizontalLayout.addWidget(self.key)
        self.randomKey = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.randomKey.setFont(font)
        self.randomKey.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.randomKey.setObjectName("randomKey")
        self.horizontalLayout.addWidget(self.randomKey)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.encryptDecrypt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encryptDecrypt.setFont(font)
        self.encryptDecrypt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.encryptDecrypt.setObjectName("encryptDecrypt")
        self.verticalLayout.addWidget(self.encryptDecrypt)
        self.output = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.pushButton_2 = QtWidgets.QPushButton(Vernam)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 380, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Vernam)
        QtCore.QMetaObject.connectSlotsByName(Vernam)

        self.vernam = ver()

        self.encryptDecrypt.clicked.connect(self.encodeText)
        self.randomKey.stateChanged.connect(self.toggleKeyInput)
        self.input.textChanged.connect(self.updateKey)

    def encodeText(self):
        text = self.input.toPlainText()
        key = self.key.text()
        enc_dec_text = self.vernam.encode(text, key)
        self.output.setText(enc_dec_text)

    def toggleKeyInput(self):
        self.key.setText('')
        if self.randomKey.isChecked():
            self.key.setReadOnly(True)
        else:
            self.key.setReadOnly(False)
        self.updateKey()

    def updateKey(self):
        if not self.randomKey.isChecked():
            return

        text_len = len(self.input.toPlainText())
        key_len = len(self.key.text())
        key_text = self.key.text()
        if key_len < text_len:
            key_text += ''.join(choice(RUS_LETTERS) for _ in range(text_len - key_len))
        else:
            key_text = key_text[:text_len]

        self.key.setText(key_text)

    def retranslateUi(self, Vernam):
        _translate = QtCore.QCoreApplication.translate
        Vernam.setWindowTitle(_translate("Vernam", "Vernam"))
        self.cypherName.setText(_translate("Vernam", "Вернам"))
        self.key.setPlaceholderText(_translate("Vernam", "Ключ"))
        self.randomKey.setText(_translate("Vernam", "Случайный ключ"))
        self.encryptDecrypt.setText(_translate("Vernam", "Зашифровать/Расшифровать"))
        self.pushButton_2.setText(_translate("Vernam", "PushButton"))