# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vigenereWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cyphers.vigenere_cypher import Vigenere as vig


class Ui_Vigenere(object):
    def setupUi(self, Vigenere):
        Vigenere.setObjectName("Vigenere")
        Vigenere.resize(484, 376)
        self.widget = QtWidgets.QWidget(Vigenere)
        self.widget.setGeometry(QtCore.QRect(40, 10, 411, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.key = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrypt.setFont(font)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout.addWidget(self.encrypt)
        self.decrypt = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decrypt.setFont(font)
        self.decrypt.setObjectName("decrypt")
        self.horizontalLayout.addWidget(self.decrypt)
        self.lang = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang.setFont(font)
        self.lang.setObjectName("lang")
        self.lang.addItem("")
        self.lang.addItem("")
        self.horizontalLayout.addWidget(self.lang)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(Vigenere)
        QtCore.QMetaObject.connectSlotsByName(Vigenere)

        self.vigenere = vig()

        self.encrypt.clicked.connect(self.encodeText)
        self.decrypt.clicked.connect(self.decodeText)

        self.lang.currentTextChanged.connect(self.changeLang)

    def encodeText(self):
        plaintext = self.input.toPlainText()
        key = self.key.text()
        cyphertext = self.vigenere.encode(plaintext, key)
        self.output.setText(cyphertext)

    def decodeText(self):
        cyphertext = self.input.toPlainText()
        key = self.key.text()
        plaintext = self.vigenere.decode(cyphertext, key)
        self.output.setText(plaintext)

    def changeLang(self):
        self.vigenere = vig(lang=self.lang.currentText())

    def retranslateUi(self, Vigenere):
        _translate = QtCore.QCoreApplication.translate
        Vigenere.setWindowTitle(_translate("Vigenere", "Vigenere"))
        self.label.setText(_translate("Vigenere", "Виженер"))
        self.encrypt.setText(_translate("Vigenere", "Зашифровать"))
        self.decrypt.setText(_translate("Vigenere", "Расшифровать"))
        self.lang.setItemText(0, _translate("Vigenere", "ENG"))
        self.lang.setItemText(1, _translate("Vigenere", "RUS"))
