# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

from cyphers.xor_cypher import XOR as xor


class Ui_XOR(object):
    def setupUi(self, XOR):
        XOR.setObjectName("XOR")
        XOR.resize(484, 374)
        self.layoutWidget = QtWidgets.QWidget(XOR)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 411, 332))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cypherName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cypherName.setFont(font)
        self.cypherName.setAlignment(QtCore.Qt.AlignCenter)
        self.cypherName.setObjectName("cypherName")
        self.verticalLayout.addWidget(self.cypherName)
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seed = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.seed.setFont(font)
        self.seed.setReadOnly(False)
        self.seed.setObjectName("seed")
        self.horizontalLayout.addWidget(self.seed)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.encryptDecrypt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encryptDecrypt.setFont(font)
        self.encryptDecrypt.setObjectName("encryptDecrypt")
        self.verticalLayout.addWidget(self.encryptDecrypt)
        self.output = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)

        self.retranslateUi(XOR)
        QtCore.QMetaObject.connectSlotsByName(XOR)

        self.encryptDecrypt.clicked.connect(self.encodeText)

        self.xor = xor()

        reg_ex = QRegExp(r'[0-9]+')
        input_validator = QRegExpValidator(reg_ex, self.seed)
        self.seed.setValidator(input_validator)

    def encodeText(self):
        if seed := self.seed.text():
            text = self.input.toPlainText()
            enc_dec_text = self.xor.encode(text, int(seed))
            self.output.setText(enc_dec_text)

    def retranslateUi(self, XOR):
        _translate = QtCore.QCoreApplication.translate
        XOR.setWindowTitle(_translate("XOR", "XOR"))
        self.cypherName.setText(_translate("XOR", "XOR"))
        self.seed.setPlaceholderText(_translate("XOR", "seed"))
        self.encryptDecrypt.setText(_translate("XOR", "Зашифровать/Расшифровать"))
