# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polyCryptanalysisWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from utils.polyalphabetic_cypher_cryptanalysis.kasiski import Kasiski
from utils.polyalphabetic_cypher_cryptanalysis.coincidence import Coincidence
from utils.polyalphabetic_cypher_cryptanalysis.autocorrelation import Autocorrelation

class Ui_PolyalphabeticCryptanalysis(object):
    def setupUi(self, PolyalphabeticCryptanalysis):
        PolyalphabeticCryptanalysis.setObjectName("PolyalphabeticCryptanalysis")
        PolyalphabeticCryptanalysis.resize(1029, 703)
        self.layoutWidget = QtWidgets.QWidget(PolyalphabeticCryptanalysis)
        self.layoutWidget.setGeometry(QtCore.QRect(17, 20, 991, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mode = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mode.setFont(font)
        self.mode.setFrame(True)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.horizontalLayout_2.addWidget(self.mode)
        self.lang = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lang.setFont(font)
        self.lang.setObjectName("lang")
        self.lang.addItem("")
        self.lang.addItem("")
        self.horizontalLayout_2.addWidget(self.lang)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.input = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.verticalLayout_2.addWidget(self.input)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findKey = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.findKey.setFont(font)
        self.findKey.setObjectName("findKey")
        self.horizontalLayout.addWidget(self.findKey)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.read = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.read.setFont(font)
        self.read.setObjectName("read")
        self.verticalLayout.addWidget(self.read)
        self.keyLengthLabel = QtWidgets.QLabel(self.layoutWidget)
        self.keyLengthLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.keyLengthLabel.setFont(font)
        self.keyLengthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.keyLengthLabel.setObjectName("keyLengthLabel")
        self.verticalLayout.addWidget(self.keyLengthLabel)
        self.keys = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.keys.setFont(font)
        self.keys.setFrame(True)
        self.keys.setObjectName("keys")
        self.verticalLayout.addWidget(self.keys)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(PolyalphabeticCryptanalysis)
        QtCore.QMetaObject.connectSlotsByName(PolyalphabeticCryptanalysis)

        self.coincidence = Coincidence()
        self.autocorrelation = Autocorrelation()
        self.kasiski = Kasiski()

        self.keyLengthLabel.hide()
        self.keys.hide()

        self.findKey.clicked.connect(self.invokeMethod)
        self.read.clicked.connect(self.readFromFile)

    def invokeMethod(self):
        for i in reversed(range(self.keys.count())):
            self.keys.removeItem(i)

        method = self.mode.currentIndex()
        if method == 0:
            keys = self.coincidence.get_key(self.input.toPlainText(), self.lang.currentText())

            if keys is None:
                return

            for key in keys:
                self.keys.addItem(key)
            key_length = len(keys[0])
            self.keys.show()

        elif method == 1:
            key = self.autocorrelation.get_key(self.input.toPlainText(), self.lang.currentText())
            self.keys.addItem(key)
            key_length = len(key)
            self.keys.show()

        else:
            key_length = self.kasiski.find_key_length(self.input.toPlainText())
            self.keys.hide()

        self.keyLengthLabel.setText(f'Длина ключа: {key_length}')
        self.keyLengthLabel.show()

    def readFromFile(self):
        path = QFileDialog.getOpenFileName()[0]
        extension = path.split('/')[-1].split('.')[-1]

        if extension != 'txt':
            print('Ошибка формата файла')

        with open(path, 'r', encoding='utf-8') as file:
            text = file.read()
            self.input.setText(text)

    def retranslateUi(self, PolyalphabeticCryptanalysis):
        _translate = QtCore.QCoreApplication.translate
        PolyalphabeticCryptanalysis.setWindowTitle(_translate("PolyalphabeticCryptanalysis", "Polyalphabetic Cryptanalysis"))
        self.mode.setItemText(0, _translate("PolyalphabeticCryptanalysis", "Метод индекса совпадений"))
        self.mode.setItemText(1, _translate("PolyalphabeticCryptanalysis", "Автокорреляционный метод"))
        self.mode.setItemText(2, _translate("PolyalphabeticCryptanalysis", "Тест Казиски"))
        self.lang.setItemText(0, _translate("PolyalphabeticCryptanalysis", "RUS"))
        self.lang.setItemText(1, _translate("PolyalphabeticCryptanalysis", "ENG"))
        self.findKey.setText(_translate("PolyalphabeticCryptanalysis", "Найти длину ключа и ключ"))
        self.read.setText(_translate("PolyalphabeticCryptanalysis", "Открыть файл"))
        self.keyLengthLabel.setText(_translate("PolyalphabeticCryptanalysis", "Длина ключа: "))
